updated links in section -continua a leggere-
bitRocket-dev/.github pull request #39
Opened 2022-10-27 14:09 UTC by robertovalenza-bitrocketdev

## Descrizione

rimossi i link non funzionanti e corretti quelli sbagliati nella sezione -continua a leggere

## Tipologia dell modifica - indica una o più opzioni

- [ ] 🐛 Bug fix (no breaking change)
- [x] 🆕 New feature (no breaking - aggiunge una funzionalità)
- [ ] 💄 Adjustment (modifica grafica o logica business)
- [ ] 💥 Breaking change (bug fix o aggiunge una funzionalità che potrebbe non essere supportare sulle versione precedenti)

## Testat su - indica uno o più dispositivi

- [x] Chrome
- [ ] Explorer
- [ ] Safari
- [ ] Firefox

_Aggiungi informazioni utili per facilitare il test all'utente_

### Screenshots o video 📸 👇

2022-10-27 15:12 UTC, riccardogenova-bitrocketdev requested changes

2022-10-27 15:12 UTC, riccardogenova-bitrocketdev commented on cv/GIOVANNI_CV.md
> +- 👨🏻‍💻 [Modalità di Ingaggio](https://github.com/bitRocket-dev/.github/blob/main/pages/ABOUT.md)
Lasciamo soltanto il `Torna alla Home` e `Modalità di Ingaggio`

2022-10-27 15:12 UTC, riccardogenova-bitrocketdev commented on cv/GIULIANO_CV.md
> +- 👨🏻‍💻 [Modalità di Ingaggio](https://github.com/bitRocket-dev/.github/blob/main/pages/ABOUT.md)
Lasciamo soltanto il `Torna alla Home` e `Modalità di Ingaggio`

2022-10-27 15:12 UTC, riccardogenova-bitrocketdev commented on cv/ROBERTO_L_CV.md
> +- 👨🏻‍💻 [Modalità di Ingaggio](https://github.com/bitRocket-dev/.github/blob/main/pages/ABOUT.md)
Lasciamo soltanto il `Torna alla Home` e `Modalità di Ingaggio`

2022-10-27 15:12 UTC, riccardogenova-bitrocketdev commented on cv/ROBERTO_P_CV.md
> +- 👨🏻‍💻 [Modalità di Ingaggio](https://github.com/bitRocket-dev/.github/blob/main/pages/ABOUT.md)
Lasciamo soltanto il `Torna alla Home` e `Modalità di Ingaggio`

2022-10-27 15:12 UTC, riccardogenova-bitrocketdev commented on cv/VINCENZO_CV.md
>  - 🚀 [Perché scegliere bitRocket.dev](https://github.com/bitRocket-dev/.github/blob/main/pages/WHY_BITROCKET-DEV.md)
Lasciamo soltanto il `Torna alla Home` e `Modalità di Ingaggio`

2022-10-28 09:09 UTC, riccardogenova-bitrocketdev commented on cv/GIORGIO_CV.md
> +- 👨🏻‍💻 [Modalità di Ingaggio](https://github.com/bitRocket-dev/.github/blob/main/pages/ABOUT.md)
Correggere in `Modalità d'ingaggio`

2022-10-28 10:02 UTC, danielemaione-bitrocketdev approved these changes

2022-10-28 11:26 UTC, riccardogenova-bitrocketdev requested changes

2022-10-28 11:26 UTC, riccardogenova-bitrocketdev commented on cv/GIORGIO_CV.md
> +- 👨🏻‍💻 [Modalità di'ingaggio](https://github.com/bitRocket-dev/.github/blob/main/pages/ABOUT.md)
Modalità d'ingaggio

2022-10-28 11:26 UTC, riccardogenova-bitrocketdev commented on cv/GIOVANNI_CV.md
> +- 👨🏻‍💻 [Modalità di'ingaggio](https://github.com/bitRocket-dev/.github/blob/main/pages/ABOUT.md)
!!

2022-10-28 13:38 UTC, riccardogenova-bitrocketdev approved these changes

2022-10-28 14:16 UTC, riccardogenova-bitrocketdev approved these changes

2022-10-28 14:35 UTC, merged