Cambiata spaziatura tra le immagini dei client.
bitRocket-dev/.github pull request #42
Opened 2022-10-27 14:38 UTC by giorgiosangiorgi-bitrocketdev

## Descrizione

Cambiata spaziatura tra le immagini dei client con l'aggiunta di un padding di 5px.

## Tipologia dell modifica - indica una o più opzioni

- [ ] 🐛 Bug fix (no breaking change)
- [ ] 🆕 New feature (no breaking - aggiunge una funzionalità)
- [X] 💄 Adjustment (modifica grafica o logica business)
- [ ] 💥 Breaking change (bug fix o aggiunge una funzionalità che potrebbe non essere supportare sulle versione precedenti)

## Testato su - indica uno o più dispositivi

- [X] Chrome
- [ ] Explorer
- [ ] Safari
- [ ] Firefox

### Screenshots o video 📸 👇
![Screenshot 2022-10-27 at 16 32 02](https://user-images.githubusercontent.com/100219140/198317528-ff3b218c-03af-433e-ae59-43bbdf8c716e.png)

2022-10-27 14:54 UTC, danielemaione-bitrocketdev submitted a review, later dismissed

2022-10-27 15:14 UTC, riccardogenova-bitrocketdev requested changes

2022-10-28 09:04 UTC, giorgiosangiorgi-bitrocketdev commented on profile/README.md
> +<img src="/assets/clients/unicredit_logo.png" height=35px alt='Unicredit' title='Unicredit'> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="/assets/clients/illimiti_logo.png" height=40px  alt='Illimi
![Screenshot 2022-10-28 at 11 02 57](https://user-images.githubusercontent.com/100219140/198549186-0356befb-0bb7-40b6-bfb5-d1516a2b9dce.png)

2022-10-28 09:06 UTC, danielemaione-bitrocketdev approved these changes

2022-10-28 10:54 UTC, riccardogenova-bitrocketdev approved these changes

2022-10-28 11:27 UTC, riccardogenova-bitrocketdev approved these changes

2022-10-28 11:27 UTC, merged