docs: fix/dev-tab
bitRocket-dev/.github pull request #55
Opened 2022-10-28 15:58 UTC by danielemaione-bitrocketdev

Aggiustata tabella dei developer

- [ ] 🐛 Bug fix (no breaking change)
- [ ] 🆕 New feature (no breaking - aggiunge una funzionalità)
- [x] 💄 Adjustment (modifica grafica o logica business)
- [ ] 💥 Breaking change (bug fix o aggiunge una funzionalità che potrebbe non essere supportare sulle versione precedenti)

## Testato su - indica uno o più dispositivi

- [x] Chrome
- [ ] Explorer
- [ ] Safari
- [ ] Firefox

![Schermata 2022-10-28 alle 17 57 03](https://user-images.githubusercontent.com/115459945/198681106-32e1d4c3-3330-41fe-9731-06a52fe11c8c.png)

2022-10-28 16:21 UTC, giorgiosangiorgi-bitrocketdev submitted a review, later dismissed

2022-10-31 08:54 UTC, riccardogenova-bitrocketdev approved these changes

2022-10-31 09:12 UTC, gabrielepolizzotto-bitrocketdev submitted a review, later dismissed

2022-10-31 09:13 UTC, giorgiosangiorgi-bitrocketdev approved these changes

2022-10-31 11:07 UTC, riccardogenova-bitrocketdev requested changes
Sistemare commit...

2022-10-31 11:22 UTC, giorgiosangiorgi-bitrocketdev approved these changes

2022-10-31 11:25 UTC, giorgiosangiorgi-bitrocketdev approved these changes

2022-10-31 11:27 UTC, gabrielepolizzotto-bitrocketdev approved these changes

2022-10-31 11:31 UTC, riccardogenova-bitrocketdev approved these changes

2022-10-31 11:33 UTC, giorgiosangiorgi-bitrocketdev approved these changes

2022-10-31 11:33 UTC, merged